services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
      POSTGRES_DB: ledger_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
      POSTGRES_DB: ledger_test_db
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ledger_user:ledger_pass@db:5432/ledger_db
    ports:
      - "8000:8000"

volumes:
  pgdata: