"""allow nullable transfer_id for non-transfer ledger entries (deposits)

Revision ID: 1ceabcae370b
Revises: ec5a827c0fc8
Create Date: 2026-07-26 13:40:29.154546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ceabcae370b'
down_revision: Union[str, Sequence[str], None] = 'ec5a827c0fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'transfer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'transfer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
